const express = require('express');
const helmet = require('helmet');
const bcrypt = require('bcryptjs');
const crypto = require('crypto');
const { Pool } = require('pg');
const fs = require('fs');
const path = require('path');

const PORT = process.env.PORT || 10000;
const DATABASE_URL = process.env.DATABASE_URL;
const DIRECTOR_EMAIL = String(process.env.OWNER_EMAIL || 'makwandegcora23@gmail.com').trim().toLowerCase();
if (!DATABASE_URL) { console.error('DATABASE_URL is required for production.'); process.exit(1); }
const pool = new Pool({ connectionString: DATABASE_URL, ssl: { rejectUnauthorized: false } });
const app = express();
app.use(helmet({ contentSecurityPolicy:false }));
app.use(express.json({limit:'3mb'}));
app.use(express.static(path.join(__dirname,'public'),{maxAge:'1m'}));

const sessions=new Map();
const token=()=>crypto.randomBytes(32).toString('hex');
const tempPassword=()=>`Es!${crypto.randomBytes(6).toString('base64url')}9`;
const auth=(req,res,next)=>{const t=(req.headers.authorization||'').replace(/^Bearer\s+/i,'');const s=sessions.get(t);if(!s)return res.status(401).json({error:'Authentication required'});req.user=s;next();};
const managementRoles=['DIRECTOR','MANAGING_DIRECTOR','ADMINISTRATOR','MANAGER'];
const manager=(req,res,next)=>managementRoles.includes(req.user.role)?next():res.status(403).json({error:'Management permission required'});
const director=(req,res,next)=>(req.user.role==='DIRECTOR'&&req.user.email===DIRECTOR_EMAIL)?next():res.status(403).json({error:'Director authorisation required'});
const audit=async(actor,action,entity,entityId,details={})=>pool.query(`INSERT INTO audit_log(actor,action,entity,entity_id,details) VALUES($1,$2,$3,$4,$5)`,[actor,action,entity,entityId||null,details]);
const num=v=>Number(v||0);
const today=()=>new Date().toISOString().slice(0,10);

async function migrate(){
await pool.query(`
CREATE TABLE IF NOT EXISTS users(id BIGSERIAL PRIMARY KEY,email TEXT UNIQUE NOT NULL,password_hash TEXT NOT NULL,role TEXT NOT NULL,active BOOLEAN NOT NULL DEFAULT TRUE,created_at TIMESTAMPTZ NOT NULL DEFAULT now());
CREATE TABLE IF NOT EXISTS products(sku TEXT PRIMARY KEY,category TEXT NOT NULL,name TEXT NOT NULL,serving TEXT NOT NULL,selling_price NUMERIC(12,2) NOT NULL CHECK(selling_price>=0),active BOOLEAN NOT NULL DEFAULT TRUE,created_at TIMESTAMPTZ NOT NULL DEFAULT now());
CREATE TABLE IF NOT EXISTS inventory(sku TEXT PRIMARY KEY REFERENCES products(sku) ON DELETE CASCADE,qty NUMERIC(14,3) NOT NULL DEFAULT 0,unit_cost NUMERIC(12,2),reorder_level NUMERIC(14,3) NOT NULL DEFAULT 0,updated_at TIMESTAMPTZ NOT NULL DEFAULT now());
CREATE TABLE IF NOT EXISTS stock_movements(id BIGSERIAL PRIMARY KEY,sku TEXT NOT NULL REFERENCES products(sku),movement_type TEXT NOT NULL,qty NUMERIC(14,3) NOT NULL,unit_cost NUMERIC(12,2),reference TEXT,note TEXT,actor TEXT NOT NULL,created_at TIMESTAMPTZ NOT NULL DEFAULT now());
CREATE TABLE IF NOT EXISTS sales(id BIGSERIAL PRIMARY KEY,receipt_no TEXT UNIQUE NOT NULL,payment_method TEXT NOT NULL,subtotal NUMERIC(12,2) NOT NULL,cash_tendered NUMERIC(12,2),change_due NUMERIC(12,2),actor TEXT NOT NULL,created_at TIMESTAMPTZ NOT NULL DEFAULT now());
CREATE TABLE IF NOT EXISTS sale_items(id BIGSERIAL PRIMARY KEY,sale_id BIGINT NOT NULL REFERENCES sales(id) ON DELETE CASCADE,sku TEXT NOT NULL REFERENCES products(sku),qty NUMERIC(14,3) NOT NULL,unit_price NUMERIC(12,2) NOT NULL,line_total NUMERIC(12,2) NOT NULL);
CREATE TABLE IF NOT EXISTS expenses(id BIGSERIAL PRIMARY KEY,category TEXT NOT NULL,description TEXT NOT NULL,amount NUMERIC(12,2) NOT NULL CHECK(amount>=0),payment_method TEXT NOT NULL,reference TEXT,actor TEXT NOT NULL,created_at TIMESTAMPTZ NOT NULL DEFAULT now());
CREATE TABLE IF NOT EXISTS cashups(id BIGSERIAL PRIMARY KEY,business_date DATE NOT NULL,opening_float NUMERIC(12,2) NOT NULL DEFAULT 0,expected_cash NUMERIC(12,2) NOT NULL,actual_cash NUMERIC(12,2) NOT NULL,variance NUMERIC(12,2) NOT NULL,card_total NUMERIC(12,2) NOT NULL DEFAULT 0,eft_total NUMERIC(12,2) NOT NULL DEFAULT 0,notes TEXT,actor TEXT NOT NULL,created_at TIMESTAMPTZ NOT NULL DEFAULT now());
CREATE TABLE IF NOT EXISTS infrastructure_status(id BIGSERIAL PRIMARY KEY,battery_percent NUMERIC(5,2),solar_kw NUMERIC(8,2),water_percent NUMERIC(5,2),internet_status TEXT,note TEXT,actor TEXT NOT NULL,created_at TIMESTAMPTZ NOT NULL DEFAULT now());
CREATE TABLE IF NOT EXISTS audit_log(id BIGSERIAL PRIMARY KEY,actor TEXT NOT NULL,action TEXT NOT NULL,entity TEXT NOT NULL,entity_id TEXT,details JSONB NOT NULL DEFAULT '{}'::jsonb,created_at TIMESTAMPTZ NOT NULL DEFAULT now());
CREATE TABLE IF NOT EXISTS merchant_settlements(id BIGSERIAL PRIMARY KEY,business_date DATE NOT NULL,channel TEXT NOT NULL,gross_amount NUMERIC(12,2) NOT NULL CHECK(gross_amount>=0),fees NUMERIC(12,2) NOT NULL DEFAULT 0 CHECK(fees>=0),net_amount NUMERIC(12,2) NOT NULL CHECK(net_amount>=0),reference TEXT,status TEXT NOT NULL DEFAULT 'PENDING',notes TEXT,actor TEXT NOT NULL,created_at TIMESTAMPTZ NOT NULL DEFAULT now());
CREATE TABLE IF NOT EXISTS suppliers(id BIGSERIAL PRIMARY KEY,name TEXT NOT NULL,contact_person TEXT,phone TEXT,email TEXT,address TEXT,tax_no TEXT,payment_terms TEXT,active BOOLEAN NOT NULL DEFAULT TRUE,notes TEXT,created_at TIMESTAMPTZ NOT NULL DEFAULT now());
CREATE TABLE IF NOT EXISTS purchase_orders(id BIGSERIAL PRIMARY KEY,po_no TEXT UNIQUE NOT NULL,supplier_id BIGINT REFERENCES suppliers(id),status TEXT NOT NULL DEFAULT 'DRAFT',order_date DATE NOT NULL DEFAULT current_date,expected_date DATE,reference TEXT,notes TEXT,approved_by TEXT,total NUMERIC(12,2) NOT NULL DEFAULT 0,created_by TEXT NOT NULL,created_at TIMESTAMPTZ NOT NULL DEFAULT now());
CREATE TABLE IF NOT EXISTS purchase_order_items(id BIGSERIAL PRIMARY KEY,po_id BIGINT NOT NULL REFERENCES purchase_orders(id) ON DELETE CASCADE,sku TEXT NOT NULL REFERENCES products(sku),qty NUMERIC(14,3) NOT NULL,mode TEXT NOT NULL DEFAULT 'UNIT',unit_cost NUMERIC(12,2) NOT NULL,total NUMERIC(12,2) NOT NULL,received_qty NUMERIC(14,3) NOT NULL DEFAULT 0);
CREATE TABLE IF NOT EXISTS stock_counts(id BIGSERIAL PRIMARY KEY,count_no TEXT UNIQUE NOT NULL,business_date DATE NOT NULL DEFAULT current_date,status TEXT NOT NULL DEFAULT 'OPEN',notes TEXT,created_by TEXT NOT NULL,approved_by TEXT,created_at TIMESTAMPTZ NOT NULL DEFAULT now(),closed_at TIMESTAMPTZ);
CREATE TABLE IF NOT EXISTS stock_count_items(id BIGSERIAL PRIMARY KEY,count_id BIGINT NOT NULL REFERENCES stock_counts(id) ON DELETE CASCADE,sku TEXT NOT NULL REFERENCES products(sku),system_qty NUMERIC(14,3) NOT NULL,physical_qty NUMERIC(14,3),variance NUMERIC(14,3));
CREATE TABLE IF NOT EXISTS events(id BIGSERIAL PRIMARY KEY,event_no TEXT UNIQUE NOT NULL,event_type TEXT NOT NULL,event_name TEXT NOT NULL,client_name TEXT,client_phone TEXT,event_date DATE NOT NULL,guest_count INTEGER,venue TEXT,total_amount NUMERIC(12,2) NOT NULL DEFAULT 0,deposit_amount NUMERIC(12,2) NOT NULL DEFAULT 0,balance NUMERIC(12,2) NOT NULL DEFAULT 0,status TEXT NOT NULL DEFAULT 'BOOKED',notes TEXT,created_by TEXT NOT NULL,created_at TIMESTAMPTZ NOT NULL DEFAULT now());
CREATE TABLE IF NOT EXISTS event_payments(id BIGSERIAL PRIMARY KEY,event_id BIGINT NOT NULL REFERENCES events(id) ON DELETE CASCADE,amount NUMERIC(12,2) NOT NULL,payment_method TEXT NOT NULL,reference TEXT,actor TEXT NOT NULL,created_at TIMESTAMPTZ NOT NULL DEFAULT now());
CREATE TABLE IF NOT EXISTS shifts(id BIGSERIAL PRIMARY KEY,user_id BIGINT REFERENCES users(id),business_date DATE NOT NULL DEFAULT current_date,opened_at TIMESTAMPTZ NOT NULL DEFAULT now(),closed_at TIMESTAMPTZ,opening_float NUMERIC(12,2) NOT NULL DEFAULT 0,closing_cash NUMERIC(12,2),expected_cash NUMERIC(12,2),variance NUMERIC(12,2),status TEXT NOT NULL DEFAULT 'OPEN',actor TEXT NOT NULL);
CREATE TABLE IF NOT EXISTS sale_adjustments(id BIGSERIAL PRIMARY KEY,sale_id BIGINT REFERENCES sales(id),adjustment_type TEXT NOT NULL,amount NUMERIC(12,2) NOT NULL DEFAULT 0,reason TEXT,approved_by TEXT NOT NULL,created_at TIMESTAMPTZ NOT NULL DEFAULT now());
CREATE TABLE IF NOT EXISTS business_settings(setting_key TEXT PRIMARY KEY,setting_value JSONB NOT NULL,updated_by TEXT NOT NULL,updated_at TIMESTAMPTZ NOT NULL DEFAULT now());
CREATE TABLE IF NOT EXISTS role_permissions(role TEXT NOT NULL,permission TEXT NOT NULL,allowed BOOLEAN NOT NULL DEFAULT TRUE,PRIMARY KEY(role,permission));
ALTER TABLE products ADD COLUMN IF NOT EXISTS brand TEXT;
ALTER TABLE products ADD COLUMN IF NOT EXISTS size_label TEXT;
ALTER TABLE products ADD COLUMN IF NOT EXISTS units_per_case INTEGER NOT NULL DEFAULT 1;
ALTER TABLE products ADD COLUMN IF NOT EXISTS case_price NUMERIC(12,2);
ALTER TABLE products ADD COLUMN IF NOT EXISTS age_restricted BOOLEAN NOT NULL DEFAULT FALSE;
ALTER TABLE products ADD COLUMN IF NOT EXISTS manually_added BOOLEAN NOT NULL DEFAULT FALSE;
ALTER TABLE products ADD COLUMN IF NOT EXISTS expiry_tracking BOOLEAN NOT NULL DEFAULT FALSE;
ALTER TABLE users ADD COLUMN IF NOT EXISTS full_name TEXT;
ALTER TABLE users ADD COLUMN IF NOT EXISTS employee_no TEXT;
ALTER TABLE users ADD COLUMN IF NOT EXISTS phone TEXT;
ALTER TABLE users ADD COLUMN IF NOT EXISTS job_title TEXT;
ALTER TABLE users ADD COLUMN IF NOT EXISTS department TEXT;
ALTER TABLE users ADD COLUMN IF NOT EXISTS hire_date DATE;
ALTER TABLE users ADD COLUMN IF NOT EXISTS access_note TEXT;
ALTER TABLE users ADD COLUMN IF NOT EXISTS must_change_password BOOLEAN NOT NULL DEFAULT FALSE;
ALTER TABLE users ADD COLUMN IF NOT EXISTS last_login_at TIMESTAMPTZ;
ALTER TABLE sales ADD COLUMN IF NOT EXISTS discount_amount NUMERIC(12,2) NOT NULL DEFAULT 0;
ALTER TABLE sales ADD COLUMN IF NOT EXISTS status TEXT NOT NULL DEFAULT 'COMPLETED';
ALTER TABLE sales ADD COLUMN IF NOT EXISTS table_ref TEXT;
`);
const catPath=path.join(__dirname,'data','catalogue.json');
if(fs.existsSync(catPath)){const cat=JSON.parse(fs.readFileSync(catPath,'utf8'));const c=await pool.connect();try{await c.query('BEGIN');for(const p of cat){await c.query(`INSERT INTO products(sku,category,name,serving,selling_price,active,brand,size_label,units_per_case,case_price,age_restricted) VALUES($1,$2,$3,$4,$5,$6,$7,$8,$9,$10,$11) ON CONFLICT(sku) DO NOTHING`,[p.sku,p.category,p.name,p.serving,num(p.selling_price_zar),p.active!==false,p.brand||p.name,p.size_label||p.serving,Number(p.units_per_case||1),p.case_price_zar==null?null:num(p.case_price_zar),!!p.age_restricted]);await c.query(`INSERT INTO inventory(sku) VALUES($1) ON CONFLICT(sku) DO NOTHING`,[p.sku]);}await c.query('COMMIT');}catch(e){await c.query('ROLLBACK');throw e;}finally{c.release();}}
const {rows:[d]}=await pool.query(`SELECT id FROM users WHERE lower(email)=lower($1)`,[DIRECTOR_EMAIL]);
if(!d){const pw=process.env.OWNER_PASSWORD;if(!pw)throw new Error('OWNER_PASSWORD is required to create Director account');const hash=await bcrypt.hash(pw,12);await pool.query(`INSERT INTO users(email,password_hash,role,active,full_name,job_title,department,must_change_password) VALUES($1,$2,'DIRECTOR',TRUE,'Makwande Gcora','Director','Executive',FALSE)`,[DIRECTOR_EMAIL,hash]);}
await pool.query(`UPDATE users SET role='DIRECTOR',active=TRUE,must_change_password=FALSE WHERE lower(email)=lower($1)`,[DIRECTOR_EMAIL]);
}

app.get('/health',async(req,res)=>{try{await pool.query('SELECT 1');res.json({ok:true,service:'Esingesini Lounge Operations'});}catch(e){res.status(503).json({ok:false,error:'database unavailable'});}});
app.post('/api/login',async(req,res)=>{const email=String(req.body.email||'').trim().toLowerCase(),pw=String(req.body.password||'');const {rows}=await pool.query(`SELECT id,email,password_hash,role,active,must_change_password FROM users WHERE lower(email)=lower($1)`,[email]);const u=rows[0];if(!u||!u.active||!(await bcrypt.compare(pw,u.password_hash)))return res.status(401).json({error:'Invalid credentials'});await pool.query(`UPDATE users SET last_login_at=now() WHERE id=$1`,[u.id]);const s={id:u.id,email:u.email.toLowerCase(),role:u.role,must_change_password:u.must_change_password};const t=token();sessions.set(t,s);await audit(u.email,'LOGIN','SESSION',null,{});res.json({token:t,user:s});});
app.get('/api/me',auth,(req,res)=>res.json(req.user));
app.post('/api/logout',auth,(req,res)=>{const t=(req.headers.authorization||'').replace(/^Bearer\s+/i,'');sessions.delete(t);res.json({ok:true});});
app.post('/api/change-password',auth,async(req,res)=>{const cur=String(req.body.current_password||''),next=String(req.body.new_password||'');if(next.length<10)return res.status(400).json({error:'New password must be at least 10 characters'});const {rows:[u]}=await pool.query(`SELECT password_hash FROM users WHERE id=$1`,[req.user.id]);if(!u||!(await bcrypt.compare(cur,u.password_hash)))return res.status(400).json({error:'Current password is incorrect'});const hash=await bcrypt.hash(next,12);await pool.query(`UPDATE users SET password_hash=$2,must_change_password=FALSE WHERE id=$1`,[req.user.id,hash]);req.user.must_change_password=false;await audit(req.user.email,'PASSWORD_CHANGED','USER',String(req.user.id),{});res.json({ok:true});});

app.get('/api/catalogue',auth,async(req,res)=>{const all=req.user.role==='DIRECTOR'&&req.query.all==='1';const {rows}=await pool.query(`SELECT p.*,p.selling_price::float selling_price,p.case_price::float case_price,i.qty::float stock_qty,i.unit_cost::float unit_cost,i.reorder_level::float reorder_level FROM products p JOIN inventory i USING(sku) ${all?'':'WHERE p.active=TRUE'} ORDER BY p.category,p.name,p.size_label`);res.json(rows);});
app.post('/api/products',auth,director,async(req,res)=>{const b=req.body||{},sku=String(b.sku||'').trim().toUpperCase(),price=num(b.selling_price),units=Math.max(1,parseInt(b.units_per_case||1,10));if(!sku||!b.name||!b.category||!b.size_label||price<0)return res.status(400).json({error:'SKU, name, category, size and valid price required'});try{await pool.query(`INSERT INTO products(sku,category,name,brand,serving,size_label,selling_price,units_per_case,case_price,age_restricted,expiry_tracking,active,manually_added) VALUES($1,$2,$3,$4,$5,$5,$6,$7,$8,$9,$10,$11,TRUE)`,[sku,String(b.category).toUpperCase(),String(b.name),String(b.brand||b.name),String(b.size_label),price,units,b.case_price===''||b.case_price==null?null:num(b.case_price),!!b.age_restricted,!!b.expiry_tracking,b.active!==false]);await pool.query(`INSERT INTO inventory(sku,reorder_level) VALUES($1,$2)`,[sku,num(b.reorder_level)]);await audit(req.user.email,'PRODUCT_CREATED','PRODUCT',sku,{price});res.json({ok:true,sku});}catch(e){res.status(400).json({error:e.code==='23505'?'SKU already exists':e.message});}});
app.put('/api/products/:sku',auth,director,async(req,res)=>{const b=req.body||{};const r=await pool.query(`UPDATE products SET category=$2,name=$3,brand=$4,serving=$5,size_label=$5,selling_price=$6,units_per_case=$7,case_price=$8,age_restricted=$9,expiry_tracking=$10,active=$11 WHERE sku=$1`,[req.params.sku,String(b.category||'OTHER').toUpperCase(),String(b.name||''),String(b.brand||b.name||''),String(b.size_label||''),num(b.selling_price),Math.max(1,parseInt(b.units_per_case||1,10)),b.case_price===''||b.case_price==null?null:num(b.case_price),!!b.age_restricted,!!b.expiry_tracking,b.active!==false]);if(!r.rowCount)return res.status(404).json({error:'Product not found'});await pool.query(`UPDATE inventory SET reorder_level=$2 WHERE sku=$1`,[req.params.sku,num(b.reorder_level)]);await audit(req.user.email,'PRODUCT_UPDATED','PRODUCT',req.params.sku,{});res.json({ok:true});});
app.delete('/api/products/:sku',auth,director,async(req,res)=>{const sku=req.params.sku;const {rows:[u]}=await pool.query(`SELECT (SELECT count(*) FROM sale_items WHERE sku=$1)+(SELECT count(*) FROM stock_movements WHERE sku=$1) n`,[sku]);if(num(u.n)>0){await pool.query(`UPDATE products SET active=FALSE WHERE sku=$1`,[sku]);return res.json({ok:true,archived:true});}await pool.query(`DELETE FROM products WHERE sku=$1`,[sku]);res.json({ok:true});});

app.get('/api/users',auth,director,async(req,res)=>{const {rows}=await pool.query(`SELECT id,email,role,active,full_name,employee_no,phone,job_title,department,hire_date,access_note,must_change_password,last_login_at,created_at FROM users ORDER BY CASE role WHEN 'DIRECTOR' THEN 1 WHEN 'MANAGING_DIRECTOR' THEN 2 WHEN 'ADMINISTRATOR' THEN 3 WHEN 'MANAGER' THEN 4 ELSE 5 END,id`);res.json(rows);});
app.post('/api/users',auth,director,async(req,res)=>{const b=req.body||{},email=String(b.email||'').trim().toLowerCase(),role=String(b.role||'').toUpperCase();if(!email||!['MANAGING_DIRECTOR','ADMINISTRATOR','MANAGER','CASHIER','STOCK'].includes(role))return res.status(400).json({error:'Valid staff email and role required'});const pw=String(b.password||'')||tempPassword();const emp=String(b.employee_no||'').trim()||`ES-${Date.now().toString().slice(-6)}`;try{const hash=await bcrypt.hash(pw,12);const {rows:[u]}=await pool.query(`INSERT INTO users(email,password_hash,role,active,full_name,employee_no,phone,job_title,department,hire_date,access_note,must_change_password) VALUES($1,$2,$3,TRUE,$4,$5,$6,$7,$8,$9,$10,TRUE) RETURNING id,email,role,full_name,employee_no`,[email,hash,role,b.full_name||null,emp,b.phone||null,b.job_title||null,b.department||'Operations',b.hire_date||null,b.access_note||null]);await audit(req.user.email,'STAFF_REGISTERED','USER',String(u.id),{role,emp});res.json({ok:true,user:u,temporary_password:pw});}catch(e){res.status(400).json({error:e.code==='23505'?'Email already exists':e.message});}});
app.put('/api/users/:id',auth,director,async(req,res)=>{const id=Number(req.params.id);const {rows:[u]}=await pool.query(`SELECT * FROM users WHERE id=$1`,[id]);if(!u)return res.status(404).json({error:'User not found'});if(u.email.toLowerCase()===DIRECTOR_EMAIL&&(req.body.active===false||String(req.body.role||'DIRECTOR').toUpperCase()!=='DIRECTOR'))return res.status(400).json({error:'Director cannot be disabled or demoted'});const role=String(req.body.role||u.role).toUpperCase();await pool.query(`UPDATE users SET role=$2,active=$3,full_name=COALESCE($4,full_name),phone=COALESCE($5,phone),job_title=COALESCE($6,job_title),department=COALESCE($7,department),access_note=COALESCE($8,access_note) WHERE id=$1`,[id,role,req.body.active!==false,req.body.full_name??null,req.body.phone??null,req.body.job_title??null,req.body.department??null,req.body.access_note??null]);let generated=null;if(req.body.generate_password){generated=tempPassword();const hash=await bcrypt.hash(generated,12);await pool.query(`UPDATE users SET password_hash=$2,must_change_password=TRUE WHERE id=$1`,[id,hash]);}await audit(req.user.email,'STAFF_UPDATED','USER',String(id),{role});res.json({ok:true,temporary_password:generated});});
app.get('/api/administration',auth,director,async(req,res)=>{const {rows}=await pool.query(`SELECT role,count(*)::int total,count(*) FILTER(WHERE active)::int active FROM users GROUP BY role ORDER BY role`);res.json({director_email:DIRECTOR_EMAIL,hierarchy:['DIRECTOR','MANAGING_DIRECTOR','ADMINISTRATOR','MANAGER','CASHIER','STOCK'],summary:rows});});

app.get('/api/dashboard',auth,async(req,res)=>{const {rows:[s]}=await pool.query(`SELECT COALESCE(sum(subtotal-discount_amount) FILTER(WHERE status='COMPLETED'),0)::float sales,COALESCE(sum(subtotal-discount_amount) FILTER(WHERE payment_method='CASH' AND status='COMPLETED'),0)::float cash,COALESCE(sum(subtotal-discount_amount) FILTER(WHERE payment_method='CARD' AND status='COMPLETED'),0)::float card,COALESCE(sum(subtotal-discount_amount) FILTER(WHERE payment_method='EFT' AND status='COMPLETED'),0)::float eft,count(*) FILTER(WHERE status='COMPLETED')::int transactions FROM sales WHERE created_at::date=current_date`);const {rows:[e]}=await pool.query(`SELECT COALESCE(sum(amount),0)::float expenses FROM expenses WHERE created_at::date=current_date`);const {rows:[st]}=await pool.query(`SELECT COALESCE(sum(COALESCE(unit_cost,0)*qty),0)::float stock_value,count(*) FILTER(WHERE p.active AND qty<=reorder_level)::int low_stock FROM inventory i JOIN products p USING(sku)`);const {rows:[ev]}=await pool.query(`SELECT count(*) FILTER(WHERE event_date>=current_date AND status NOT IN('CANCELLED','COMPLETED'))::int upcoming_events,COALESCE(sum(balance) FILTER(WHERE event_date>=current_date AND status NOT IN('CANCELLED','COMPLETED')),0)::float event_balance FROM events`);const {rows:[alerts]}=await pool.query(`SELECT count(*) FILTER(WHERE i.qty<=i.reorder_level AND p.active)::int low_stock FROM inventory i JOIN products p USING(sku)`);res.json({...s,...e,...st,...ev,alerts:alerts.low_stock});});
app.get('/api/director-dashboard',auth,director,async(req,res)=>{const {rows:[cash]}=await pool.query(`SELECT COALESCE(sum(abs(variance)),0)::float cash_variance FROM cashups WHERE business_date>=current_date-interval '7 days'`);const {rows:[stock]}=await pool.query(`SELECT count(*)::int stock_issues,COALESCE(sum(abs(variance)),0)::float unit_variance FROM stock_count_items sci JOIN stock_counts sc ON sc.id=sci.count_id WHERE sc.business_date>=current_date-interval '30 days' AND COALESCE(variance,0)<>0`);const {rows:[events]}=await pool.query(`SELECT count(*) FILTER(WHERE balance>0 AND event_date>=current_date)::int unpaid_events,COALESCE(sum(balance) FILTER(WHERE balance>0 AND event_date>=current_date),0)::float outstanding FROM events`);const {rows:[settle]}=await pool.query(`SELECT count(*) FILTER(WHERE status<>'RECONCILED')::int unresolved FROM merchant_settlements WHERE business_date>=current_date-interval '7 days'`);const {rows:[staff]}=await pool.query(`SELECT count(*) FILTER(WHERE active)::int active_staff FROM users`);res.json({...cash,...stock,...events,...settle,...staff});});

app.get('/api/billing',auth,manager,async(req,res)=>{const d=req.query.date||today();const {rows:[s]}=await pool.query(`SELECT COALESCE(sum(subtotal-discount_amount) FILTER(WHERE status='COMPLETED'),0)::float total_sales,COALESCE(sum(subtotal-discount_amount) FILTER(WHERE payment_method='CASH' AND status='COMPLETED'),0)::float cash_sales,COALESCE(sum(subtotal-discount_amount) FILTER(WHERE payment_method='CARD' AND status='COMPLETED'),0)::float card_sales,COALESCE(sum(subtotal-discount_amount) FILTER(WHERE payment_method='EFT' AND status='COMPLETED'),0)::float eft_sales FROM sales WHERE created_at::date=$1`,[d]);const {rows:[e]}=await pool.query(`SELECT COALESCE(sum(amount),0)::float expenses,COALESCE(sum(amount) FILTER(WHERE payment_method='CASH'),0)::float cash_expenses FROM expenses WHERE created_at::date=$1`,[d]);const {rows:settlements}=await pool.query(`SELECT * FROM merchant_settlements WHERE business_date=$1 ORDER BY id DESC`,[d]);const {rows:[m]}=await pool.query(`SELECT COALESCE(sum(net_amount) FILTER(WHERE channel='CAPITEC_CARD'),0)::float capitec_card_net,COALESCE(sum(net_amount) FILTER(WHERE channel='CAPITEC_EFT'),0)::float capitec_eft_net,COALESCE(sum(net_amount) FILTER(WHERE channel='CASH_BANKING'),0)::float cash_banked FROM merchant_settlements WHERE business_date=$1`,[d]);res.json({date:d,...s,...e,...m,unsettled_card:Number((s.card_sales-m.capitec_card_net).toFixed(2)),cash_available:Number((s.cash_sales-e.cash_expenses-m.cash_banked).toFixed(2)),settlements});});
app.post('/api/merchant-settlements',auth,manager,async(req,res)=>{const b=req.body||{},d=b.business_date||today(),channel=String(b.channel||'').toUpperCase(),gross=num(b.gross_amount),fees=num(b.fees),net=b.net_amount==null||b.net_amount===''?gross-fees:num(b.net_amount),status=String(b.status||'PENDING').toUpperCase();if(!['CAPITEC_CARD','CAPITEC_EFT','CASH_BANKING'].includes(channel))return res.status(400).json({error:'Invalid channel'});const {rows:[r]}=await pool.query(`INSERT INTO merchant_settlements(business_date,channel,gross_amount,fees,net_amount,reference,status,notes,actor) VALUES($1,$2,$3,$4,$5,$6,$7,$8,$9) RETURNING *`,[d,channel,gross,fees,net,b.reference||null,status,b.notes||null,req.user.email]);await audit(req.user.email,'SETTLEMENT_RECORDED','SETTLEMENT',String(r.id),{channel});res.json(r);});

app.post('/api/stock/receive',auth,manager,async(req,res)=>{const b=req.body||{};let qty=num(b.qty),cost=num(b.unit_cost),mode=String(b.mode||'UNIT').toUpperCase();const {rows:[p]}=await pool.query(`SELECT units_per_case FROM products WHERE sku=$1`,[b.sku]);if(!p||qty<=0)return res.status(400).json({error:'Valid product and quantity required'});if(mode==='CASE'){qty*=p.units_per_case;cost/=p.units_per_case;}const c=await pool.connect();try{await c.query('BEGIN');await c.query(`UPDATE inventory SET qty=qty+$2,unit_cost=$3,updated_at=now() WHERE sku=$1`,[b.sku,qty,cost]);await c.query(`INSERT INTO stock_movements(sku,movement_type,qty,unit_cost,reference,note,actor) VALUES($1,'RECEIPT',$2,$3,$4,$5,$6)`,[b.sku,qty,cost,b.reference||null,b.note||null,req.user.email]);await c.query('COMMIT');await audit(req.user.email,'STOCK_RECEIVED','PRODUCT',b.sku,{qty});res.json({ok:true});}catch(e){await c.query('ROLLBACK');res.status(400).json({error:e.message});}finally{c.release();}});
app.post('/api/stock/opening',auth,director,async(req,res)=>{const items=Array.isArray(req.body.items)?req.body.items:[];const c=await pool.connect();try{await c.query('BEGIN');for(const i of items){const q=num(i.qty),cost=i.unit_cost==null?null:num(i.unit_cost);await c.query(`UPDATE inventory SET qty=$2,unit_cost=COALESCE($3,unit_cost),updated_at=now() WHERE sku=$1`,[i.sku,q,cost]);await c.query(`INSERT INTO stock_movements(sku,movement_type,qty,unit_cost,reference,note,actor) VALUES($1,'OPENING',$2,$3,'OPENING-STOCK','Opening physical stock',$4)`,[i.sku,q,cost,req.user.email]);}await c.query('COMMIT');await audit(req.user.email,'OPENING_STOCK_CAPTURED','INVENTORY',null,{items:items.length});res.json({ok:true});}catch(e){await c.query('ROLLBACK');res.status(400).json({error:e.message});}finally{c.release();}});

app.post('/api/sales',auth,async(req,res)=>{const items=Array.isArray(req.body.items)?req.body.items:[],method=String(req.body.payment_method||'').toUpperCase();if(!items.length||!['CASH','CARD','EFT'].includes(method))return res.status(400).json({error:'Items and payment method required'});const c=await pool.connect();try{await c.query('BEGIN');let subtotal=0;const priced=[];for(const i of items){const count=num(i.qty);const {rows:[p]}=await c.query(`SELECT p.sku,p.name,p.selling_price::float,p.case_price::float,p.units_per_case,i.qty::float stock_qty FROM products p JOIN inventory i USING(sku) WHERE p.sku=$1 AND p.active=TRUE FOR UPDATE`,[i.sku]);if(!p||count<=0)throw new Error('Invalid item');const isCase=String(i.mode||'UNIT').toUpperCase()==='CASE',stockQty=isCase?count*p.units_per_case:count;if(p.stock_qty<stockQty)throw new Error('Insufficient stock for '+p.name);const price=isCase?(p.case_price==null?p.selling_price*p.units_per_case:p.case_price):p.selling_price,line=Number((price*count).toFixed(2));subtotal+=line;priced.push({...p,stockQty,price,line,isCase});}const discount=Math.min(Math.max(num(req.body.discount_amount),0),subtotal),total=Number((subtotal-discount).toFixed(2)),tender=req.body.cash_tendered==null?null:num(req.body.cash_tendered);if(method==='CASH'&&tender<total)throw new Error('Cash tendered below total');const change=method==='CASH'?Number((tender-total).toFixed(2)):null,ref='ES-'+Date.now().toString(36).toUpperCase()+'-'+crypto.randomBytes(2).toString('hex').toUpperCase();const {rows:[sale]}=await c.query(`INSERT INTO sales(receipt_no,payment_method,subtotal,discount_amount,cash_tendered,change_due,actor,table_ref) VALUES($1,$2,$3,$4,$5,$6,$7,$8) RETURNING id,created_at`,[ref,method,subtotal,discount,tender,change,req.user.email,req.body.table_ref||null]);for(const p of priced){await c.query(`INSERT INTO sale_items(sale_id,sku,qty,unit_price,line_total) VALUES($1,$2,$3,$4,$5)`,[sale.id,p.sku,p.stockQty,p.price,p.line]);await c.query(`UPDATE inventory SET qty=qty-$2 WHERE sku=$1`,[p.sku,p.stockQty]);await c.query(`INSERT INTO stock_movements(sku,movement_type,qty,reference,actor,note) VALUES($1,'SALE',$2,$3,$4,$5)`,[p.sku,-p.stockQty,ref,req.user.email,p.isCase?'CASE SALE':'UNIT SALE']);}await c.query('COMMIT');await audit(req.user.email,'SALE_COMPLETED','SALE',ref,{total,discount});res.json({ok:true,receipt_no:ref,total,subtotal,discount,change_due:change,created_at:sale.created_at});}catch(e){await c.query('ROLLBACK');res.status(400).json({error:e.message});}finally{c.release();}});
app.post('/api/sales/:id/void',auth,manager,async(req,res)=>{const id=Number(req.params.id);const c=await pool.connect();try{await c.query('BEGIN');const {rows:[s]}=await c.query(`SELECT * FROM sales WHERE id=$1 FOR UPDATE`,[id]);if(!s||s.status!=='COMPLETED')throw new Error('Sale cannot be voided');const {rows:items}=await c.query(`SELECT * FROM sale_items WHERE sale_id=$1`,[id]);for(const i of items){await c.query(`UPDATE inventory SET qty=qty+$2 WHERE sku=$1`,[i.sku,i.qty]);await c.query(`INSERT INTO stock_movements(sku,movement_type,qty,reference,note,actor) VALUES($1,'VOID_RETURN',$2,$3,$4,$5)`,[i.sku,i.qty,s.receipt_no,req.body.reason||'Voided sale',req.user.email]);}await c.query(`UPDATE sales SET status='VOIDED' WHERE id=$1`,[id]);await c.query(`INSERT INTO sale_adjustments(sale_id,adjustment_type,reason,approved_by) VALUES($1,'VOID',$2,$3)`,[id,req.body.reason||null,req.user.email]);await c.query('COMMIT');await audit(req.user.email,'SALE_VOIDED','SALE',String(id),{});res.json({ok:true});}catch(e){await c.query('ROLLBACK');res.status(400).json({error:e.message});}finally{c.release();}});
app.get('/api/sales/recent',auth,manager,async(req,res)=>{const {rows}=await pool.query(`SELECT id,receipt_no,payment_method,(subtotal-discount_amount)::float total,status,actor,created_at FROM sales ORDER BY id DESC LIMIT 100`);res.json(rows);});

app.get('/api/suppliers',auth,manager,async(req,res)=>{const {rows}=await pool.query(`SELECT * FROM suppliers ORDER BY active DESC,name`);res.json(rows);});
app.post('/api/suppliers',auth,manager,async(req,res)=>{const b=req.body||{};if(!b.name)return res.status(400).json({error:'Supplier name required'});const {rows:[r]}=await pool.query(`INSERT INTO suppliers(name,contact_person,phone,email,address,tax_no,payment_terms,notes) VALUES($1,$2,$3,$4,$5,$6,$7,$8) RETURNING *`,[b.name,b.contact_person||null,b.phone||null,b.email||null,b.address||null,b.tax_no||null,b.payment_terms||null,b.notes||null]);await audit(req.user.email,'SUPPLIER_CREATED','SUPPLIER',String(r.id),{});res.json(r);});
app.put('/api/suppliers/:id',auth,manager,async(req,res)=>{const b=req.body||{};const {rows:[r]}=await pool.query(`UPDATE suppliers SET name=$2,contact_person=$3,phone=$4,email=$5,address=$6,tax_no=$7,payment_terms=$8,active=$9,notes=$10 WHERE id=$1 RETURNING *`,[Number(req.params.id),b.name,b.contact_person||null,b.phone||null,b.email||null,b.address||null,b.tax_no||null,b.payment_terms||null,b.active!==false,b.notes||null]);if(!r)return res.status(404).json({error:'Supplier not found'});res.json(r);});

app.get('/api/purchase-orders',auth,manager,async(req,res)=>{const {rows}=await pool.query(`SELECT po.*,s.name supplier_name FROM purchase_orders po LEFT JOIN suppliers s ON s.id=po.supplier_id ORDER BY po.id DESC LIMIT 100`);res.json(rows);});
app.post('/api/purchase-orders',auth,manager,async(req,res)=>{const b=req.body||{},items=Array.isArray(b.items)?b.items:[];if(!items.length)return res.status(400).json({error:'At least one PO item required'});const poNo='PO-'+Date.now().toString(36).toUpperCase();const c=await pool.connect();try{await c.query('BEGIN');let total=0;for(const i of items)total+=num(i.qty)*num(i.unit_cost);const {rows:[po]}=await c.query(`INSERT INTO purchase_orders(po_no,supplier_id,status,order_date,expected_date,reference,notes,total,created_by) VALUES($1,$2,'DRAFT',$3,$4,$5,$6,$7,$8) RETURNING *`,[poNo,b.supplier_id||null,b.order_date||today(),b.expected_date||null,b.reference||null,b.notes||null,total,req.user.email]);for(const i of items)await c.query(`INSERT INTO purchase_order_items(po_id,sku,qty,mode,unit_cost,total) VALUES($1,$2,$3,$4,$5,$6)`,[po.id,i.sku,num(i.qty),String(i.mode||'UNIT').toUpperCase(),num(i.unit_cost),num(i.qty)*num(i.unit_cost)]);await c.query('COMMIT');await audit(req.user.email,'PO_CREATED','PURCHASE_ORDER',poNo,{total});res.json(po);}catch(e){await c.query('ROLLBACK');res.status(400).json({error:e.message});}finally{c.release();}});
app.post('/api/purchase-orders/:id/approve',auth,director,async(req,res)=>{const {rows:[r]}=await pool.query(`UPDATE purchase_orders SET status='APPROVED',approved_by=$2 WHERE id=$1 AND status='DRAFT' RETURNING *`,[Number(req.params.id),req.user.email]);if(!r)return res.status(400).json({error:'PO not found or not draft'});await audit(req.user.email,'PO_APPROVED','PURCHASE_ORDER',r.po_no,{});res.json(r);});
app.post('/api/purchase-orders/:id/receive',auth,manager,async(req,res)=>{const id=Number(req.params.id);const c=await pool.connect();try{await c.query('BEGIN');const {rows:[po]}=await c.query(`SELECT * FROM purchase_orders WHERE id=$1 FOR UPDATE`,[id]);if(!po||!['APPROVED','PART_RECEIVED'].includes(po.status))throw new Error('PO must be approved');const {rows:items}=await c.query(`SELECT poi.*,p.units_per_case FROM purchase_order_items poi JOIN products p USING(sku) WHERE po_id=$1`,[id]);for(const i of items){const remaining=num(i.qty)-num(i.received_qty);if(remaining<=0)continue;const units=String(i.mode).toUpperCase()==='CASE'?remaining*i.units_per_case:remaining;const unitCost=String(i.mode).toUpperCase()==='CASE'?num(i.unit_cost)/i.units_per_case:num(i.unit_cost);await c.query(`UPDATE inventory SET qty=qty+$2,unit_cost=$3 WHERE sku=$1`,[i.sku,units,unitCost]);await c.query(`INSERT INTO stock_movements(sku,movement_type,qty,unit_cost,reference,note,actor) VALUES($1,'PO_RECEIPT',$2,$3,$4,$5,$6)`,[i.sku,units,unitCost,po.po_no,'Purchase order receipt',req.user.email]);await c.query(`UPDATE purchase_order_items SET received_qty=qty WHERE id=$1`,[i.id]);}await c.query(`UPDATE purchase_orders SET status='RECEIVED' WHERE id=$1`,[id]);await c.query('COMMIT');await audit(req.user.email,'PO_RECEIVED','PURCHASE_ORDER',po.po_no,{});res.json({ok:true});}catch(e){await c.query('ROLLBACK');res.status(400).json({error:e.message});}finally{c.release();}});

app.get('/api/stock-counts',auth,manager,async(req,res)=>{const {rows}=await pool.query(`SELECT * FROM stock_counts ORDER BY id DESC LIMIT 50`);res.json(rows);});
app.post('/api/stock-counts',auth,manager,async(req,res)=>{const no='SC-'+Date.now().toString(36).toUpperCase();const c=await pool.connect();try{await c.query('BEGIN');const {rows:[sc]}=await c.query(`INSERT INTO stock_counts(count_no,business_date,notes,created_by) VALUES($1,$2,$3,$4) RETURNING *`,[no,req.body.business_date||today(),req.body.notes||null,req.user.email]);const {rows:inv}=await c.query(`SELECT sku,qty FROM inventory`);for(const i of inv)await c.query(`INSERT INTO stock_count_items(count_id,sku,system_qty) VALUES($1,$2,$3)`,[sc.id,i.sku,i.qty]);await c.query('COMMIT');res.json(sc);}catch(e){await c.query('ROLLBACK');res.status(400).json({error:e.message});}finally{c.release();}});
app.get('/api/stock-counts/:id/items',auth,manager,async(req,res)=>{const {rows}=await pool.query(`SELECT sci.*,p.name,p.size_label FROM stock_count_items sci JOIN products p USING(sku) WHERE count_id=$1 ORDER BY p.category,p.name`,[Number(req.params.id)]);res.json(rows);});
app.put('/api/stock-counts/:id/items',auth,manager,async(req,res)=>{const items=Array.isArray(req.body.items)?req.body.items:[];for(const i of items)await pool.query(`UPDATE stock_count_items SET physical_qty=$3,variance=$3-system_qty WHERE count_id=$1 AND sku=$2`,[Number(req.params.id),i.sku,num(i.physical_qty)]);res.json({ok:true});});
app.post('/api/stock-counts/:id/close',auth,director,async(req,res)=>{const id=Number(req.params.id);const c=await pool.connect();try{await c.query('BEGIN');const {rows:items}=await c.query(`SELECT * FROM stock_count_items WHERE count_id=$1 FOR UPDATE`,[id]);if(items.some(i=>i.physical_qty==null))throw new Error('Complete all physical counts first');for(const i of items){const v=num(i.variance);if(v!==0){await c.query(`UPDATE inventory SET qty=$2 WHERE sku=$1`,[i.sku,i.physical_qty]);await c.query(`INSERT INTO stock_movements(sku,movement_type,qty,reference,note,actor) VALUES($1,'COUNT_VARIANCE',$2,$3,'Physical stock count',$4)`,[i.sku,v,'COUNT-'+id,req.user.email]);}}await c.query(`UPDATE stock_counts SET status='CLOSED',approved_by=$2,closed_at=now() WHERE id=$1`,[id,req.user.email]);await c.query('COMMIT');await audit(req.user.email,'STOCK_COUNT_CLOSED','STOCK_COUNT',String(id),{});res.json({ok:true});}catch(e){await c.query('ROLLBACK');res.status(400).json({error:e.message});}finally{c.release();}});

app.get('/api/events',auth,manager,async(req,res)=>{const {rows}=await pool.query(`SELECT * FROM events ORDER BY event_date DESC,id DESC LIMIT 100`);res.json(rows);});
app.post('/api/events',auth,manager,async(req,res)=>{const b=req.body||{},no='EV-'+Date.now().toString(36).toUpperCase(),total=num(b.total_amount),deposit=num(b.deposit_amount);if(!b.event_type||!b.event_name||!b.event_date)return res.status(400).json({error:'Event type, name and date required'});const {rows:[e]}=await pool.query(`INSERT INTO events(event_no,event_type,event_name,client_name,client_phone,event_date,guest_count,venue,total_amount,deposit_amount,balance,status,notes,created_by) VALUES($1,$2,$3,$4,$5,$6,$7,$8,$9,$10,$11,$12,$13,$14) RETURNING *`,[no,b.event_type,b.event_name,b.client_name||null,b.client_phone||null,b.event_date,b.guest_count||null,b.venue||null,total,deposit,total-deposit,b.status||'BOOKED',b.notes||null,req.user.email]);res.json(e);});
app.post('/api/events/:id/payment',auth,manager,async(req,res)=>{const id=Number(req.params.id),amt=num(req.body.amount);if(amt<=0)return res.status(400).json({error:'Positive amount required'});await pool.query(`INSERT INTO event_payments(event_id,amount,payment_method,reference,actor) VALUES($1,$2,$3,$4,$5)`,[id,amt,req.body.payment_method||'CASH',req.body.reference||null,req.user.email]);const {rows:[e]}=await pool.query(`UPDATE events SET deposit_amount=deposit_amount+$2,balance=GREATEST(total_amount-(deposit_amount+$2),0) WHERE id=$1 RETURNING *`,[id,amt]);res.json(e);});

app.post('/api/shifts/open',auth,async(req,res)=>{const {rows:[r]}=await pool.query(`INSERT INTO shifts(user_id,business_date,opening_float,actor) VALUES($1,$2,$3,$4) RETURNING *`,[req.user.id,req.body.business_date||today(),num(req.body.opening_float),req.user.email]);res.json(r);});
app.post('/api/shifts/:id/close',auth,async(req,res)=>{const id=Number(req.params.id),actual=num(req.body.closing_cash);const {rows:[sh]}=await pool.query(`SELECT * FROM shifts WHERE id=$1 AND user_id=$2 AND status='OPEN'`,[id,req.user.id]);if(!sh)return res.status(404).json({error:'Open shift not found'});const {rows:[s]}=await pool.query(`SELECT COALESCE(sum(subtotal-discount_amount),0)::float cash FROM sales WHERE actor=$1 AND payment_method='CASH' AND created_at BETWEEN $2 AND now() AND status='COMPLETED'`,[req.user.email,sh.opened_at]);const expected=num(sh.opening_float)+num(s.cash),variance=actual-expected;const {rows:[r]}=await pool.query(`UPDATE shifts SET closed_at=now(),closing_cash=$2,expected_cash=$3,variance=$4,status='CLOSED' WHERE id=$1 RETURNING *`,[id,actual,expected,variance]);res.json(r);});

app.post('/api/expenses',auth,manager,async(req,res)=>{const b=req.body||{},amount=num(b.amount);if(!b.category||!b.description||amount<0)return res.status(400).json({error:'Valid expense required'});const {rows:[r]}=await pool.query(`INSERT INTO expenses(category,description,amount,payment_method,reference,actor) VALUES($1,$2,$3,$4,$5,$6) RETURNING *`,[b.category,b.description,amount,b.payment_method||'CASH',b.reference||null,req.user.email]);res.json(r);});
app.post('/api/cashups',auth,manager,async(req,res)=>{const d=req.body.business_date||today(),opening=num(req.body.opening_float),actual=num(req.body.actual_cash);const {rows:[s]}=await pool.query(`SELECT COALESCE(sum(subtotal-discount_amount) FILTER(WHERE payment_method='CASH' AND status='COMPLETED'),0)::float cash_sales,COALESCE(sum(subtotal-discount_amount) FILTER(WHERE payment_method='CARD' AND status='COMPLETED'),0)::float card_sales,COALESCE(sum(subtotal-discount_amount) FILTER(WHERE payment_method='EFT' AND status='COMPLETED'),0)::float eft_sales FROM sales WHERE created_at::date=$1`,[d]);const {rows:[e]}=await pool.query(`SELECT COALESCE(sum(amount),0)::float cash_expenses FROM expenses WHERE created_at::date=$1 AND payment_method='CASH'`,[d]);const expected=opening+s.cash_sales-e.cash_expenses,variance=actual-expected;const {rows:[r]}=await pool.query(`INSERT INTO cashups(business_date,opening_float,expected_cash,actual_cash,variance,card_total,eft_total,notes,actor) VALUES($1,$2,$3,$4,$5,$6,$7,$8,$9) RETURNING *`,[d,opening,expected,actual,variance,s.card_sales,s.eft_sales,req.body.notes||null,req.user.email]);res.json(r);});
app.post('/api/infrastructure',auth,manager,async(req,res)=>{const b=req.body||{};const {rows:[r]}=await pool.query(`INSERT INTO infrastructure_status(battery_percent,solar_kw,water_percent,internet_status,note,actor) VALUES($1,$2,$3,$4,$5,$6) RETURNING *`,[b.battery_percent===''?null:num(b.battery_percent),b.solar_kw===''?null:num(b.solar_kw),b.water_percent===''?null:num(b.water_percent),b.internet_status||null,b.note||null,req.user.email]);res.json(r);});
app.get('/api/audit',auth,manager,async(req,res)=>{const {rows}=await pool.query(`SELECT * FROM audit_log ORDER BY id DESC LIMIT 500`);res.json(rows);});

app.get('/api/reports/summary',auth,manager,async(req,res)=>{const from=req.query.from||today(),to=req.query.to||today();const {rows:[sales]}=await pool.query(`SELECT COALESCE(sum(subtotal-discount_amount) FILTER(WHERE status='COMPLETED'),0)::float revenue,COALESCE(sum(si.qty*COALESCE(i.unit_cost,0)) FILTER(WHERE s.status='COMPLETED'),0)::float cogs FROM sales s LEFT JOIN sale_items si ON si.sale_id=s.id LEFT JOIN inventory i ON i.sku=si.sku WHERE s.created_at::date BETWEEN $1 AND $2`,[from,to]);const {rows:[exp]}=await pool.query(`SELECT COALESCE(sum(amount),0)::float expenses FROM expenses WHERE created_at::date BETWEEN $1 AND $2`,[from,to]);const gross=sales.revenue-sales.cogs,net=gross-exp.expenses;const {rows:top}=await pool.query(`SELECT p.name,p.size_label,sum(si.qty)::float qty,sum(si.line_total)::float sales FROM sale_items si JOIN sales s ON s.id=si.sale_id JOIN products p ON p.sku=si.sku WHERE s.status='COMPLETED' AND s.created_at::date BETWEEN $1 AND $2 GROUP BY p.name,p.size_label ORDER BY sales DESC LIMIT 10`,[from,to]);res.json({from,to,revenue:sales.revenue,cogs:sales.cogs,gross_profit:gross,expenses:exp.expenses,net_operating_result:net,top_products:top});});
app.get('/api/alerts',auth,manager,async(req,res)=>{const {rows:low}=await pool.query(`SELECT p.sku,p.name,p.size_label,i.qty::float qty,i.reorder_level::float reorder_level FROM inventory i JOIN products p USING(sku) WHERE p.active AND i.qty<=i.reorder_level ORDER BY i.qty`);const {rows:cash}=await pool.query(`SELECT id,business_date,variance::float variance FROM cashups WHERE abs(variance)>0 ORDER BY id DESC LIMIT 20`);const {rows:events}=await pool.query(`SELECT id,event_no,event_name,event_date,balance::float balance FROM events WHERE balance>0 AND event_date>=current_date ORDER BY event_date LIMIT 20`);res.json({low_stock:low,cash_variances:cash,unpaid_events:events});});
app.get('/api/settings',auth,director,async(req,res)=>{const {rows}=await pool.query(`SELECT setting_key,setting_value FROM business_settings ORDER BY setting_key`);res.json(rows);});
app.put('/api/settings/:key',auth,director,async(req,res)=>{await pool.query(`INSERT INTO business_settings(setting_key,setting_value,updated_by) VALUES($1,$2,$3) ON CONFLICT(setting_key) DO UPDATE SET setting_value=excluded.setting_value,updated_by=excluded.updated_by,updated_at=now()`,[req.params.key,req.body.value,req.user.email]);res.json({ok:true});});

app.use((req,res,next)=>{if(req.path.startsWith('/api/')||req.path==='/health')return next();res.sendFile(path.join(__dirname,'public','index.html'));});
migrate().then(()=>app.listen(PORT,()=>console.log(`Esingesini Lounge Operations listening on ${PORT}`))).catch(e=>{console.error(e);process.exit(1);});
